package Pojo;
// Generated 19/07/2015 07:01:41 PM by Hibernate Tools 4.3.1


import java.sql.Date;



/**
 * Tusuario generated by hbm2java
 */
public class Tusuario implements java.io.Serializable{


     private int codigoUsuario;
     private String nombre;
     private String primerApellido;
     private String segundoApellido;
     private String correoElectronico;
     private String contrasenha;
     private String sexo;
     private String telefono;
     private String txtConfirmarContraseña;
     private String  fechaNacimiento;
     

    public Tusuario() {
    }

    public int getCodigoUsuario() {
        return codigoUsuario;
    }

    public void setCodigoUsuario(int codigoUsuario) {
        this.codigoUsuario = codigoUsuario;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getPrimerApellido() {
        return primerApellido;
    }

    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }

    public String getSegundoApellido() {
        return segundoApellido;
    }

    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }

    public String getCorreoElectronico() {
        return correoElectronico;
    }

    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }

    public String getContrasenha() {
        return contrasenha;
    }

    public void setContrasenha(String contrasenha) {
        this.contrasenha = contrasenha;
    }

    
    public String getSexo() {
        return sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    public String getTelefono() {
        return telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getTxtConfirmarContraseña() {
        return txtConfirmarContraseña;
    }

    public void setTxtConfirmarContraseña(String txtConfirmarContraseña) {
        this.txtConfirmarContraseña = txtConfirmarContraseña;
    }

    public String getFechaNacimiento() {
        return fechaNacimiento;
    }

    public void setFechaNacimiento(String fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    @Override
    public String toString() {
        return "Tusuario{" + "codigoUsuario=" + codigoUsuario + ", nombre=" + nombre + ", primerApellido=" + primerApellido + ", segundoApellido=" + segundoApellido + ", correoElectronico=" + correoElectronico + ", contrasenha=" + contrasenha + ", sexo=" + sexo + ", telefono=" + telefono + '}';
    }
}


